-- =====================================================
-- الجزء المتبقي من النسخة الاحتياطية (مصحح)
-- Remaining Part of Backup (Fixed)
-- =====================================================
-- تشغل هذا الملف بعد تنفيذ الجزء الأول
-- Run this file after executing the first part
-- =====================================================

-- بيانات تقنيات الرسم (Drawing Techniques Data) - مصحح
INSERT INTO drawing_techniques (id, title, title_en, description, description_en, content, content_en, difficulty_level, difficulty_level_en, category, category_en, tools_needed, tools_needed_en, steps, steps_en, tips, tips_en, image_url, video_url, estimated_time, estimated_time_en, prerequisites, prerequisites_en, related_techniques, featured, visible, view_count, created_at, updated_at) VALUES
(1, 'تقنية التظليل بالقلم الرصاص', 'Pencil Shading Technique', 'تعلم أساسيات التظليل بالقلم الرصاص لإضافة العمق والبعد الثالث', 'Learn the basics of pencil shading to add depth and dimension to your drawings', 'التظليل هو أحد أهم التقنيات في الرسم بالقلم الرصاص. يساعد على إظهار الأبعاد والعمق في الرسمة، ويخلق تأثيرات بصرية مذهلة.', 'Shading is one of the most important techniques in pencil drawing. It helps show dimensions and depth in the drawing, creating stunning visual effects.', 'مبتدئ', 'Beginner', 'رسم تقليدي', 'Traditional Drawing', ARRAY['قلم رصاص 2B', 'قلم رصاص 4B', 'قلم رصاص 6B', 'ممحاة', 'ورق رسم'], ARRAY['2B Pencil', '4B Pencil', '6B Pencil', 'Eraser', 'Drawing Paper'], ARRAY['ابدأ برسم الشكل الأساسي', 'حدد مصدر الضوء', 'ابدأ بالظلال الفاتحة', 'أضف الظلال المتوسطة', 'أنهِ بالظلال الداكنة'], ARRAY['Start with basic shape', 'Identify light source', 'Begin with light shadows', 'Add medium shadows', 'Finish with dark shadows'], ARRAY['استخدم حركات دائرية للتظليل', 'لا تضغط بقوة على القلم', 'ابدأ بالفاتح وانتقل للداكن'], ARRAY['Use circular motions for shading', 'Do not press too hard on the pencil', 'Start light and go darker'], null, null, '30-45 دقيقة', '30-45 minutes', ARRAY['معرفة أساسيات الرسم'], ARRAY['Basic drawing knowledge'], null, true, true, 0, '2025-06-13 23:53:05.748224+00', '2025-06-13 23:53:05.748224+00'),
(2, 'رسم البورتريه بالقلم الرصاص', 'Portrait Drawing with Pencil', 'تعلم أساسيات رسم الوجوه بالقلم الرصاص بطريقة احترافية', 'Learn the basics of drawing faces with pencil in a professional way', 'رسم البورتريه يتطلب فهم نسب الوجه وتشريحه. سنتعلم كيفية رسم العينين والأنف والفم بدقة.', 'Portrait drawing requires understanding facial proportions and anatomy. We will learn how to draw eyes, nose, and mouth accurately.', 'متوسط', 'Intermediate', 'رسم تقليدي', 'Traditional Drawing', ARRAY['قلم رصاص HB', 'قلم رصاص 2B', 'قلم رصاص 4B', 'ممحاة', 'مسطرة'], ARRAY['HB Pencil', '2B Pencil', '4B Pencil', 'Eraser', 'Ruler'], ARRAY['رسم الشكل البيضاوي للوجه', 'تحديد مواقع العينين', 'رسم الأنف', 'رسم الفم', 'إضافة التفاصيل'], ARRAY['Draw oval face shape', 'Mark eye positions', 'Draw the nose', 'Draw the mouth', 'Add details'], ARRAY['استخدم قاعدة الثلث لتقسيم الوجه', 'ابدأ بالعين اليسرى', 'انتبه للنسب بين الملامح'], ARRAY['Use rule of thirds for face division', 'Start with left eye', 'Pay attention to proportions between features'], null, null, '60-90 دقيقة', '60-90 minutes', ARRAY['إتقان تقنية التظليل'], ARRAY['Master shading technique'], null, true, true, 0, '2025-06-13 23:55:10.812519+00', '2025-06-13 23:55:10.812519+00'),
(3, 'الرسم بالألوان المائية', 'Watercolor Painting', 'تعلم أساسيات الرسم بالألوان المائية وتقنيات المزج', 'Learn the basics of watercolor painting and blending techniques', 'الألوان المائية تتطلب تقنيات خاصة في التعامل مع الماء والألوان. سنتعلم كيفية التحكم في انتشار اللون.', 'Watercolors require special techniques in dealing with water and colors. We will learn how to control color spread.', 'مبتدئ', 'Beginner', 'ألوان مائية', 'Watercolor', ARRAY['ألوان مائية', 'فرش مختلفة الأحجام', 'ورق مائي', 'إسفنجة', 'ماء'], ARRAY['Watercolor paints', 'Different sized brushes', 'Watercolor paper', 'Sponge', 'Water'], ARRAY['تحضير الأدوات', 'بلل الورق', 'اختيار الألوان', 'البدء بالفاتح', 'إضافة التفاصيل'], ARRAY['Prepare tools', 'Wet the paper', 'Choose colors', 'Start light', 'Add details'], ARRAY['اعمل بسرعة قبل جفاف اللون', 'استخدم ماء نظيف', 'لا تخف من الأخطاء'], ARRAY['Work quickly before color dries', 'Use clean water', 'Do not be afraid of mistakes'], null, null, '45-60 دقيقة', '45-60 minutes', ARRAY[]::text[], ARRAY[]::text[], null, false, true, 0, '2025-06-13 23:55:10.812519+00', '2025-06-13 23:55:10.812519+00'),
(4, 'رسم المناظر الطبيعية', 'Landscape Drawing', 'تعلم رسم المناظر الطبيعية بالقلم الرصاص والألوان', 'Learn to draw natural landscapes with pencil and colors', 'رسم المناظر الطبيعية يتطلب فهم المنظور والعمق. سنتعلم رسم الأشجار والجبال والمياه.', 'Landscape drawing requires understanding perspective and depth. We will learn to draw trees, mountains, and water.', 'متوسط', 'Intermediate', 'رسم تقليدي', 'Traditional Drawing', ARRAY['قلم رصاص HB', 'قلم رصاص 2B', 'قلم رصاص 4B', 'ممحاة', 'منديل مزج'], ARRAY['HB Pencil', '2B Pencil', '4B Pencil', 'Eraser', 'Blending stump'], ARRAY['رسم خط الأفق', 'تحديد نقطة التلاشي', 'رسم العناصر البعيدة', 'رسم العناصر القريبة', 'إضافة التفاصيل'], ARRAY['Draw horizon line', 'Set vanishing point', 'Draw distant elements', 'Draw near elements', 'Add details'], ARRAY['ابدأ بالعناصر البعيدة أولاً', 'استخدم المنظور لإظهار العمق', 'انتبه للإضاءة الطبيعية'], ARRAY['Start with distant elements first', 'Use perspective to show depth', 'Pay attention to natural lighting'], null, null, '90-120 دقيقة', '90-120 minutes', ARRAY['فهم أساسيات المنظور'], ARRAY['Understanding perspective basics'], null, false, true, 0, '2025-06-13 23:56:32.862534+00', '2025-06-14 00:19:21.407+00'),
(5, 'الرسم الرقمي للمبتدئين', 'Digital Drawing for Beginners', 'مقدمة في الرسم الرقمي واستخدام البرامج', 'Introduction to digital drawing and software usage', 'الرسم الرقمي يفتح آفاقاً جديدة في عالم الفن. سنتعلم أساسيات استخدام البرامج والأدوات.', 'Digital drawing opens new horizons in the art world. We will learn the basics of using software and tools.', 'مبتدئ', 'Beginner', 'رسم رقمي', 'Digital Art', ARRAY['جهاز لوحي رقمي', 'قلم رقمي', 'برنامج رسم', 'حاسوب'], ARRAY['Digital tablet', 'Digital pen', 'Drawing software', 'Computer'], ARRAY['تحضير البرنامج', 'التعرف على الأدوات', 'رسم أشكال بسيطة', 'تجربة الطبقات', 'حفظ العمل'], ARRAY['Prepare software', 'Learn about tools', 'Draw simple shapes', 'Try layers', 'Save work'], ARRAY['ابدأ ببرامج مجانية', 'تدرب على استخدام الطبقات', 'لا تخف من التجريب'], ARRAY['Start with free software', 'Practice using layers', 'Do not be afraid to experiment'], null, null, '60-90 دقيقة', '60-90 minutes', ARRAY['معرفة أساسية بالحاسوب'], ARRAY['Basic computer knowledge'], null, false, true, 0, '2025-06-13 23:56:32.862534+00', '2025-06-13 23:56:32.862534+00'),
(6, 'تقنية الرسم بالفحم', 'Charcoal Drawing Technique', 'تعلم الرسم بالفحم وإنشاء تأثيرات دراماتيكية', 'Learn charcoal drawing and create dramatic effects', 'الفحم يعطي تأثيرات دراماتيكية وقوية. سنتعلم كيفية التحكم في هذه المادة وإنشاء أعمال مذهلة.', 'Charcoal gives dramatic and powerful effects. We will learn how to control this medium and create stunning works.', 'متقدم', 'Advanced', 'رسم تقليدي', 'Traditional Drawing', ARRAY['فحم طبيعي', 'فحم مضغوط', 'ممحاة عجينة', 'ورق خشن', 'منديل مزج'], ARRAY['Natural charcoal', 'Compressed charcoal', 'Kneaded eraser', 'Rough paper', 'Blending stump'], ARRAY['تحضير الورق', 'رسم الشكل العام', 'إضافة الظلال الداكنة', 'مزج الفحم', 'إضافة الإضاءة'], ARRAY['Prepare paper', 'Draw general shape', 'Add dark shadows', 'Blend charcoal', 'Add highlights'], ARRAY['اعمل في منطقة جيدة التهوية', 'استخدم مثبت الرسم', 'ابدأ بالفاتح وانتقل للداكن'], ARRAY['Work in well-ventilated area', 'Use fixative spray', 'Start light and go darker'], null, null, '120-150 دقيقة', '120-150 minutes', ARRAY['إتقان الرسم بالقلم الرصاص'], ARRAY['Master pencil drawing'], null, true, true, 0, '2025-06-13 23:56:32.862534+00', '2025-06-15 19:16:11.555+00');

-- تحديث تسلسل المعرف لتقنيات الرسم
SELECT setval('drawing_techniques_id_seq', (SELECT MAX(id) FROM drawing_techniques));

-- بيانات الإعدادات (Settings Data)
INSERT INTO settings (id, setting_key, setting_value, created_at, updated_at) VALUES
(1, 'general', '{"logo": "/1.png", "showLogo": true, "siteName": "أكاديمية ميمو للرسم", "siteNameEn": "MEMO Art Academy", "description": "تعلم فن الرسم والإبداع مع أفضل المدربين المحترفين", "descriptionEn": "Learn art and creativity with the best professional trainers", "whatsappNumber": "966501234567"}', '2025-06-13 22:38:00.454002+00', '2025-06-15 19:20:55.823+00'),
(2, 'pages', '{"showFooter": true, "showGallery": true, "showLocation": true, "showInstructors": true, "showSocialMedia": true, "socialMediaStyle": "icons"}', '2025-06-13 22:38:00.454002+00', '2025-06-15 19:20:57.344+00'),
(5, 'sections', '[{"id": "courses", "url": "#courses", "icon": "BookOpen", "name": "الدورات التدريبية", "iconBg": "bg-blue-100", "nameEn": "Training Courses", "visible": true, "iconColor": "text-blue-600"}, {"id": "instructors", "url": "#instructors", "icon": "Users", "name": "المدربون", "iconBg": "bg-green-100", "nameEn": "Instructors", "visible": true, "iconColor": "text-green-600"}, {"id": "gallery", "url": "#gallery", "icon": "Image", "name": "معرض الأعمال", "iconBg": "bg-purple-100", "nameEn": "Gallery", "visible": true, "iconColor": "text-purple-600"}, {"id": "techniques", "url": "#techniques", "icon": "PenTool", "name": "تقنيات الرسم", "iconBg": "bg-orange-100", "nameEn": "Drawing Techniques", "visible": true, "iconColor": "text-orange-600"}, {"id": "certificates", "url": "#certificates", "icon": "Award", "name": "الشهادا", "iconBg": "bg-yellow-100", "nameEn": "Certificates", "visible": false, "iconColor": "text-yellow-600"}, {"id": "schedule", "url": "#schedule", "icon": "Calendar", "name": "الجدول الزمني", "iconBg": "bg-red-100", "nameEn": "Schedule", "visible": false, "iconColor": "text-red-600"}]', '2025-06-14 22:24:16.886769+00', '2025-06-15 19:20:56.197+00'),
(9, 'socialMedia', '[{"id": "instagram", "url": "https://instagram.com/memoacademy", "icon": "Instagram", "name": "إنستغرام", "iconBg": "bg-gradient-to-br from-purple-400 to-pink-400", "nameEn": "Instagram", "visible": true, "iconColor": "text-pink-600"}, {"id": "facebook", "url": "https://facebook.com/memoacademy", "icon": "Facebook", "name": "فيسبوك", "iconBg": "bg-blue-600", "nameEn": "Facebook", "visible": true, "iconColor": "text-white"}, {"id": "youtube", "url": "https://youtube.com/@memoacademy", "icon": "YouTube", "name": "يوتيوب", "iconBg": "bg-red-600", "nameEn": "YouTube", "visible": false, "iconColor": "text-white"}, {"id": "whatsapp", "url": "https://wa.me/966501234567", "icon": "WhatsApp", "name": "واتساب", "iconBg": "bg-green-500", "nameEn": "WhatsApp", "visible": true, "iconColor": "text-white"}]', '2025-06-14 22:48:00.45845+00', '2025-06-15 19:20:56.579+00'),
(10, 'location', '{"name": "ميمو أكاديمي", "phone": "+966 50 123 4567", "nameEn": "MEMO Academy", "address": "سنباط", "mapsUrl": "https://www.google.com/maps/place/Riyadh+Saudi+Arabia/@24.7135517,46.6752957,11z", "visible": true, "addressEn": "خلف الثانوي بجوار صيدلية سحر شارع قاعة هابي سمر لاند", "coordinates": {"lat": 24.7136, "lng": 46.6753}, "workingHours": "السبت - الخميس: 9:00 ص - 9:00 م", "workingHoursEn": "Sat - Thu: 9:00 AM - 9:00 PM"}', '2025-06-14 22:48:01.824473+00', '2025-06-15 19:20:56.953+00'),
(11, 'last_sync', '"2025-06-15T19:20:57.529Z"', '2025-06-14 23:24:26.515885+00', '2025-06-15 19:20:57.721+00');

-- تحديث تسلسل المعرف للإعدادات
SELECT setval('settings_id_seq', (SELECT MAX(id) FROM settings));

-- بيانات المديرين (Admins Data)
INSERT INTO admins (id, username, email, password_hash, role, is_active, created_at, created_by, last_login, updated_at) VALUES
('2ea7fa5d-0078-4589-a379-c046a5756955', 'superadmin', 'admin@artacademy.com', '$2b$10$QCOkckjrZnFJZ/TMzFOfhu5t1.l3PSP3nEjzRxsaKA9CnxWM4tcSC', 'super_admin', true, '2025-06-14 13:59:31.392323+00', null, null, '2025-06-14 13:59:31.392323+00');

-- ملاحظة: جدول admin_sessions فارغ حالياً
-- Note: admin_sessions table is currently empty

-- إنشاء Storage Bucket (اختياري - قد يحتاج صلاحيات خاصة)
-- Create Storage Bucket (optional - may need special permissions)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('instructor-images', 'instructor-images', true, 5242880, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif'])
ON CONFLICT (id) DO NOTHING;

-- رسالة نجاح
-- Success message
SELECT 'تمت استعادة النسخة الاحتياطية بنجاح! Backup restored successfully!' as message;

-- التحقق من البيانات
-- Verify data
SELECT 
  'gallery' as table_name, COUNT(*) as records FROM gallery
UNION ALL
SELECT 'courses', COUNT(*) FROM courses
UNION ALL
SELECT 'instructors', COUNT(*) FROM instructors
UNION ALL
SELECT 'drawing_techniques', COUNT(*) FROM drawing_techniques
UNION ALL
SELECT 'settings', COUNT(*) FROM settings
UNION ALL
SELECT 'admins', COUNT(*) FROM admins;
